apiVersion: v1
kind: Service
metadata:
  name: memory-game-frontend
  namespace: memory-game
  labels:
    app: memory-game-frontend
spec:
  type: LoadBalancer
  selector:
    app: memory-game-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

